name: Build and Commit dist

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the build on
  pull_request:
    branches:
      - main # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run build # Ensure this script creates the dist/index.js file

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add dist/
          git commit -m "Build: Update dist on push"
        continue-on-error: true # If there are no changes, don't fail the workflow

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PRIVATE_REPO_ACCESS }}
