name: Build and Commit dist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you're using

      - name: Install dependencies
        run: |
          npm install
          npm install @types/node --save-dev  # Ensure @types/node is installed

      - name: Build action
        run: npm run build

      - name: Verify dist exists
        run: ls -la dist/

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add dist/
          git commit -m "Build: Update dist on push"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PRIVATE_REPO_ACCESS }}
